/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppTag: typeof import('./../components/AppTag.vue')['default']
    BaseShapeCanvas: typeof import('./../components/BaseShapeCanvas.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    DrawingStep: typeof import('./../components/DrawingStep.vue')['default']
    FormStep: typeof import('./../components/FormStep.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapePoly: typeof import('./../components/ShapePoly.vue')['default']
    ShapeRect: typeof import('./../components/ShapeRect.vue')['default']
    ShapeTrap: typeof import('./../components/ShapeTrap.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    TemplateStep: typeof import('./../components/TemplateStep.vue')['default']
    ThreeDPreview: typeof import('./../components/ThreeDPreview.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanSlider: typeof import('vant/es')['Slider']
  }
}
